workflows:
  expo-ios-workflow:
    name: Expo iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: katcha key
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.mni.katcha.social.follower.tracker
      vars:
        BUNDLE_ID: 'com.mni.katcha.social.follower.tracker'
        XCODE_WORKSPACE: 'Katcha'
        XCODE_SCHEME: 'Katcha'
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize

      - name: Add certificates to keychain
        script: |
          keychain add-certificates

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: remove all node modules
        script: |
          rm -rf node_modules yarn.lock

      - name: remove all pods
        script: |
          rm -rf ios/Pods ios/Podfile.lock

      - name: Install yarn dependencies
        script: |
          yarn install

      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install && cd ..

      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace ios/$XCODE_WORKSPACE.xcworkspace \
            --scheme $XCODE_SCHEME

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - 20shamo25@gmail.com
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: true
